export const LOAD_NETWORTH_SUCCESS = "LOAD_NETWORTH_SUCCESS";
export const LOAD_HOLDINGS_SUCCESS = "LOAD_HOLDINGS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
